apiVersion: backstage.io/v1alpha1
kind: Component
metadata:
  name: ${{values.component_id}}
  {%- if values.description %}
  description: ${{values.description}}
  {%- endif %}
  annotations:
    github.com/project-slug: ${{values.repo_project_slug}}
    dev.azure.com/build-definition: DEFRA.${{values.project_name}}
    sonarqube.org/project-key: ${{values.project_name}}
    grafana/dashboard-selector: "folderTitle == 'Managed Prometheus'"
spec:
  type: ${{ values.component_type }}
  lifecycle: ${{ values.component_lifecycle }}
  owner: ${{values.owner | dump}}
  {%- if values.system %}
  system: ${{ values.system }}
  {%- endif %}
